dataset_name: 'cardiac'

direction: 'mr2ct'

# preprocessed data dir
prep_ct_data_dir: '/mnt/data4/zyz/UDA3DSeg/public_code/ASTCMSeg/data/CT/'
prep_mr_data_dir: '/mnt/data4/zyz/UDA3DSeg/public_code/ASTCMSeg/data/MR/'

# csv dir
csv_dir: './csv/'

# train test dir
split_dir: './csv/train_test/'

# 3D prep csv
all_ct_prep_volume_data_csv_path: './csv/all_ct_prep_volume_data.csv'
all_mr_prep_volume_data_csv_path: './csv/all_mr_prep_volume_data.csv'

# 2D slices csv
all_ct_prep_slices_data_csv_path: './csv/all_ct_prep_slices_data.csv'
all_mr_prep_slices_data_csv_path: './csv/all_mr_prep_slices_data.csv'

# fake
prep_fake_t2_data_dir: '/mnt/data4/zyz/UDA3DSeg/public_code/ASTCMSeg/data/fake_mr2ct_nii/'
all_fake_t2_prep_volume_csv_path: './csv/all_fake_mr2ct_ACMIT_prep_volume.csv'
all_fake_t2_prep_slices_csv_path: './csv/all_fake_mr2ct_ACMIT_prep_slices.csv'

# self-training
prep_target_VAST_plabel_data_dir: '/mnt/data4/zyz/UDA3DSeg/public_code/ASTCMSeg/data/VAST_mr2ct_target_label/'
target_training_VAST_plabel_volume_csv_path: './csv/all_target_training_VAST_plabel_volume.csv'

# cate name to label
# Multi-tasks Cardiac Segmentation between CT and MR
cate_to_label_dict: {'bg':0, "MYO": 1,  'LAC':2, 'LVC':3, 'AA':4}
label_to_cate_dict: {'0':'bg', '1':'MYO',  '2':'LAC', '3':'LVC', '4':'AA'}
